# Generated by Django 6.0.1 on 2026-01-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('type', models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank_card', 'Bank Card'), ('visa', 'Visa')], default='cash', max_length=20)),
                ('expire_date', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wallets/')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], max_length=15)),
                ('card_type', models.CharField(choices=[('cash', 'Cash'), ('uzcard', 'UzCard'), ('humo', 'Humo'), ('visa', 'Visa')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.category')),
            ],
        ),
    ]
