# Generated by Django 6.0.1 on 2026-01-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('type', models.CharField(choices=[('income', 'INCOME'), ('outcome', 'OUTCOME')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('cash', 'CASH'), ('uzcard', 'UzCard'), ('humo', 'HUMO'), ('visa', 'VISA')], default='CASH', max_length=50)),
                ('card_numbers', models.IntegerField(blank=True, null=True)),
                ('expire_date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'INCOME'), ('outcome', 'OUTCOME')], max_length=15)),
                ('come_type', models.CharField(choices=[('cash', 'CASH'), ('uzcard', 'UzCard'), ('humo', 'HUMO'), ('visa', 'VISA')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mainapp.category')),
            ],
        ),
    ]
