# Generated by Django 6.0.1 on 2026-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallets/'),
        ),
    ]
