# Generated by Django 6.0.1 on 2026-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_wallet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
