# Generated by Django 6.0.1 on 2026-01-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_incomeoutcome_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeoutcome',
            name='come_type',
        ),
    ]
